version: '2'
services:
  web:
    build: ./web
    volumes: 
      - "./web:/usr/src/app"
    env_file: .env
    links:
      - mongo
      - redis
    depends_on:
      - mongo
  mongo:
    build: ./db
    env_file: .env
    networks:
      - default
    volumes:
      - ./db/data:/data/db/
  redis:
    image: redis
    restart: always
